### ISSUE TITLE
How to write a yaml file

### ISSUE THREAD

**Issue by ghost** [mypal/ha-mitv#1]
How to write a yaml file，Whether to support access to homekit

**Comment by mypal** [comment]
> How to write a yaml file，Whether to support access to homekit

```
binary_sensor:
  - platform: mitv_state
    host: xx.xx.xx.xx
    name: 'xxxx tv'
```

it just a binary sensor for Xiaomi TV state. recommand to use offical integration-- https://www.home-assistant.io/integrations/xiaomi_tv/
